name: Pull changes from Shopify

on:
  workflow_dispatch:
   
env:
  SHOPIFY_HOST: ${{ secrets.SHOPIFY_HOST }}
  SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
  
jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_ACTIONS_KEY }}
      # Setup node
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
        
      - name: Create and push the release branch
        run: |
          git checkout -B update-from-shopify # -B will reset branch if it exists
          git push --set-upstream --force origin update-from-shopify

      - name: Get theme
        run: node_modules/.bin/shopify-website --outputDir "$(pwd)" pull --theme '${{ secrets.THEME_NAME }}'
      
      # Assuming we want to merge into a branch of the same name in the new repo?
      - name: Commit to new branch
        run: |
          git config user.name "Github Actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Update theme from Shopify"
          git push --set-upstream --force origin update-from-shopify
          git merge main
